# Generated by Django 5.2.3 on 2025-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_task_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
